// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniversitySystem.Data;

#nullable disable

namespace UniversitySystem.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20260119034227_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniversitySystem.Models.GrupaDziekanska", b =>
                {
                    b.Property<int>("GrupaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("grupaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GrupaID"));

                    b.Property<int>("KierunekID")
                        .HasColumnType("integer")
                        .HasColumnName("kierunekid");

                    b.Property<string>("KodGrupy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kodgrupy");

                    b.Property<int>("RokStudiow")
                        .HasColumnType("integer")
                        .HasColumnName("rokstudiow");

                    b.HasKey("GrupaID");

                    b.HasIndex("KierunekID");

                    b.ToTable("grupydziekanskie");
                });

            modelBuilder.Entity("UniversitySystem.Models.Kierunek", b =>
                {
                    b.Property<int>("KierunekID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("kierunekid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KierunekID"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwa");

                    b.Property<int>("Stopien")
                        .HasColumnType("integer")
                        .HasColumnName("stopien");

                    b.Property<int>("WydzialID")
                        .HasColumnType("integer")
                        .HasColumnName("wydzialid");

                    b.HasKey("KierunekID");

                    b.HasIndex("WydzialID");

                    b.ToTable("kierunki");
                });

            modelBuilder.Entity("UniversitySystem.Models.Ocena", b =>
                {
                    b.Property<int>("OcenaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ocenaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OcenaID"));

                    b.Property<DateTime>("DataWystawienia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datawystawienia");

                    b.Property<int>("PlanZajecID")
                        .HasColumnType("integer")
                        .HasColumnName("planzajecid");

                    b.Property<int>("StudentID")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<string>("TypOceny")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("typoceny");

                    b.Property<double>("Wartosc")
                        .HasColumnType("double precision")
                        .HasColumnName("wartosc");

                    b.HasKey("OcenaID");

                    b.HasIndex("PlanZajecID");

                    b.HasIndex("StudentID");

                    b.ToTable("oceny");
                });

            modelBuilder.Entity("UniversitySystem.Models.PlanZajec", b =>
                {
                    b.Property<int>("PlanZajecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("planzajecid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanZajecID"));

                    b.Property<int>("DzienTygodnia")
                        .HasColumnType("integer")
                        .HasColumnName("dzientygodnia");

                    b.Property<TimeSpan>("GodzinaRozpoczecia")
                        .HasColumnType("interval")
                        .HasColumnName("godzinarozpoczecia");

                    b.Property<TimeSpan>("GodzinaZakonczenia")
                        .HasColumnType("interval")
                        .HasColumnName("godzinazakonczenia");

                    b.Property<int>("GrupaID")
                        .HasColumnType("integer")
                        .HasColumnName("grupaid");

                    b.Property<int>("PracownikID")
                        .HasColumnType("integer")
                        .HasColumnName("pracownikid");

                    b.Property<int>("PrzedmiotID")
                        .HasColumnType("integer")
                        .HasColumnName("przedmiotid");

                    b.Property<int>("SalaID")
                        .HasColumnType("integer")
                        .HasColumnName("salaid");

                    b.HasKey("PlanZajecID");

                    b.HasIndex("GrupaID");

                    b.HasIndex("PracownikID");

                    b.HasIndex("PrzedmiotID");

                    b.HasIndex("SalaID");

                    b.ToTable("planzajec");
                });

            modelBuilder.Entity("UniversitySystem.Models.Pracownik", b =>
                {
                    b.Property<int>("PracownikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pracownikid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PracownikID"));

                    b.Property<DateTime>("DataZatrudnienia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datazatrudnienia");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwisko");

                    b.Property<int>("StanowiskoID")
                        .HasColumnType("integer")
                        .HasColumnName("stanowiskoid");

                    b.HasKey("PracownikID");

                    b.HasIndex("StanowiskoID");

                    b.ToTable("pracownicy");
                });

            modelBuilder.Entity("UniversitySystem.Models.Przedmiot", b =>
                {
                    b.Property<int>("PrzedmiotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("przedmiotid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrzedmiotID"));

                    b.Property<int>("ECTS")
                        .HasColumnType("integer")
                        .HasColumnName("ects");

                    b.Property<int>("KierunekID")
                        .HasColumnType("integer")
                        .HasColumnName("kierunekid");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwa");

                    b.Property<int>("Semestr")
                        .HasColumnType("integer")
                        .HasColumnName("semestr");

                    b.HasKey("PrzedmiotID");

                    b.HasIndex("KierunekID");

                    b.ToTable("przedmioty");
                });

            modelBuilder.Entity("UniversitySystem.Models.Sala", b =>
                {
                    b.Property<int>("SalaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("salaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalaID"));

                    b.Property<bool>("CzyKomputery")
                        .HasColumnType("boolean")
                        .HasColumnName("czykomputery");

                    b.Property<int>("LiczbaMiejsc")
                        .HasColumnType("integer")
                        .HasColumnName("liczbamiejsc");

                    b.Property<string>("NumerSali")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numersali");

                    b.HasKey("SalaID");

                    b.ToTable("sale");
                });

            modelBuilder.Entity("UniversitySystem.Models.Stanowisko", b =>
                {
                    b.Property<int>("StanowiskoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("stanowiskoid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StanowiskoID"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwa");

                    b.Property<decimal>("StawkaGodzinowa")
                        .HasColumnType("numeric")
                        .HasColumnName("stawkagodzinowa");

                    b.HasKey("StanowiskoID");

                    b.ToTable("stanowiska");
                });

            modelBuilder.Entity("UniversitySystem.Models.StatusStudenta", b =>
                {
                    b.Property<int>("StatusStudentaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("statusstudentaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusStudentaID"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwa");

                    b.HasKey("StatusStudentaID");

                    b.ToTable("statusystudentow");
                });

            modelBuilder.Entity("UniversitySystem.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentID"));

                    b.Property<int>("GrupaID")
                        .HasColumnType("integer")
                        .HasColumnName("grupaid");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nazwisko");

                    b.Property<string>("NrIndeksu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nrindeksu");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pesel");

                    b.Property<int>("StatusStudentaID")
                        .HasColumnType("integer")
                        .HasColumnName("statusstudentaid");

                    b.HasKey("StudentID");

                    b.HasIndex("GrupaID");

                    b.HasIndex("StatusStudentaID");

                    b.ToTable("studenci");
                });

            modelBuilder.Entity("UniversitySystem.Models.Wydzial", b =>
                {
                    b.Property<int>("WydzialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wydzialid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WydzialID"));

                    b.Property<string>("Dziekan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dziekan");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nazwa");

                    b.HasKey("WydzialID");

                    b.ToTable("wydzialy");
                });

            modelBuilder.Entity("UniversitySystem.Models.GrupaDziekanska", b =>
                {
                    b.HasOne("UniversitySystem.Models.Kierunek", "Kierunek")
                        .WithMany("Grupy")
                        .HasForeignKey("KierunekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierunek");
                });

            modelBuilder.Entity("UniversitySystem.Models.Kierunek", b =>
                {
                    b.HasOne("UniversitySystem.Models.Wydzial", "Wydzial")
                        .WithMany("Kierunki")
                        .HasForeignKey("WydzialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wydzial");
                });

            modelBuilder.Entity("UniversitySystem.Models.Ocena", b =>
                {
                    b.HasOne("UniversitySystem.Models.PlanZajec", "Zajecia")
                        .WithMany("Oceny")
                        .HasForeignKey("PlanZajecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitySystem.Models.Student", "Student")
                        .WithMany("Oceny")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Zajecia");
                });

            modelBuilder.Entity("UniversitySystem.Models.PlanZajec", b =>
                {
                    b.HasOne("UniversitySystem.Models.GrupaDziekanska", "Grupa")
                        .WithMany()
                        .HasForeignKey("GrupaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitySystem.Models.Pracownik", "Pracownik")
                        .WithMany("Zajecia")
                        .HasForeignKey("PracownikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitySystem.Models.Przedmiot", "Przedmiot")
                        .WithMany("PlanZajec")
                        .HasForeignKey("PrzedmiotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitySystem.Models.Sala", "Sala")
                        .WithMany("PlanZajec")
                        .HasForeignKey("SalaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupa");

                    b.Navigation("Pracownik");

                    b.Navigation("Przedmiot");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("UniversitySystem.Models.Pracownik", b =>
                {
                    b.HasOne("UniversitySystem.Models.Stanowisko", "Stanowisko")
                        .WithMany("Pracownicy")
                        .HasForeignKey("StanowiskoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stanowisko");
                });

            modelBuilder.Entity("UniversitySystem.Models.Przedmiot", b =>
                {
                    b.HasOne("UniversitySystem.Models.Kierunek", "Kierunek")
                        .WithMany("Przedmioty")
                        .HasForeignKey("KierunekID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierunek");
                });

            modelBuilder.Entity("UniversitySystem.Models.Student", b =>
                {
                    b.HasOne("UniversitySystem.Models.GrupaDziekanska", "Grupa")
                        .WithMany("Studenci")
                        .HasForeignKey("GrupaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversitySystem.Models.StatusStudenta", "Status")
                        .WithMany("Studenci")
                        .HasForeignKey("StatusStudentaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupa");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("UniversitySystem.Models.GrupaDziekanska", b =>
                {
                    b.Navigation("Studenci");
                });

            modelBuilder.Entity("UniversitySystem.Models.Kierunek", b =>
                {
                    b.Navigation("Grupy");

                    b.Navigation("Przedmioty");
                });

            modelBuilder.Entity("UniversitySystem.Models.PlanZajec", b =>
                {
                    b.Navigation("Oceny");
                });

            modelBuilder.Entity("UniversitySystem.Models.Pracownik", b =>
                {
                    b.Navigation("Zajecia");
                });

            modelBuilder.Entity("UniversitySystem.Models.Przedmiot", b =>
                {
                    b.Navigation("PlanZajec");
                });

            modelBuilder.Entity("UniversitySystem.Models.Sala", b =>
                {
                    b.Navigation("PlanZajec");
                });

            modelBuilder.Entity("UniversitySystem.Models.Stanowisko", b =>
                {
                    b.Navigation("Pracownicy");
                });

            modelBuilder.Entity("UniversitySystem.Models.StatusStudenta", b =>
                {
                    b.Navigation("Studenci");
                });

            modelBuilder.Entity("UniversitySystem.Models.Student", b =>
                {
                    b.Navigation("Oceny");
                });

            modelBuilder.Entity("UniversitySystem.Models.Wydzial", b =>
                {
                    b.Navigation("Kierunki");
                });
#pragma warning restore 612, 618
        }
    }
}
